swagger: "2.0"
info:
  title: GAE Zero Side Effect Stack
  version: 0.0.1
host: gae-zero-side-effect-stack.appspot.com
x-google-endpoints:
  -
    name: gae-zero-side-effect-stack.appspot.com
    allowCors: true
paths:
  /people:
    get:
      operationId: getPeople
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Person"
definitions:
  Person:
    type: object
    properties:
      name:
        type: string
      country:
        type: string
      city:
        type: string
      salary:
        type: string
